RAW_DATA: 'raw_data'
INGREDIENT_DATA: 'ingredient_data'
CUISINE_DATA: 'cuisine_data'
ALLRECIPE_DATA: 'allrecipe_data'
ALLRECIPE_DB: 'allrecipe_db.pickle'
BASIC_INGREDIENTS: 'basic_ingredients.json'
APPEARANCE_RATE: 'appearance_rate.json'
SIMILARITY_COEFFICIENT: 'similarity_coefficient.pickle'
EQUIVALENCE_INDEX: 'equivalence_index.pickle'
REPLACEMENT_TABLE: 'replacement_table.json'
TYPED_REPLACEMENT_TABLE: 'typed_replacement_table.json'
INGREDIENT_FILE: 'ingr_info.tsv'
INGREDIENT_FLAVORS: 'ingr_comp.tsv'
DOWNLOAD_USDA: 'https://www.ars.usda.gov/ARSUserFiles/80400525/Data/BFPDB/BFPD_csv_07132018.zip'
USDA_ZIP: 'USDA.zip'
USDA_PRODUCTS: 'Products.csv'
USDA_NUTRIENTS: 'Nutrients.csv'
SIMILAR_INGREDIENTS: 'similar_ingredients.pickle'
INGREDIENT_NUTRIENTS: 'ingredient_nutrients.pickle'
CUISINE_CHARACTERISTICS: 'cuisine_characteristics.pickle'
SAFE_REQUEST_INTERVAL: [15, 25]