RAW_DATA: 'raw_data'
INGREDIENT_DATA: 'ingredient_data'
CUISINE_DATA: 'cuisine_data'
INGREDIENT_FILE: 'ingr_info.tsv'
INGREDIENT_FLAVORS: 'ingr_comp.tsv'
DOWNLOAD_USDA: 'https://www.ars.usda.gov/ARSUserFiles/80400525/Data/BFPDB/BFPD_csv_07132018.zip'
USDA_ZIP: 'USDA.zip'
USDA_PRODUCTS: 'Products.csv'
USDA_NUTRIENTS: 'Nutrients.csv'
SIMILAR_INGREDIENTS: 'similar_ingredients.pickle'
INGREDIENT_NUTRIENTS: 'ingredient_nutrients.pickle'
CUISINE_CHARACTERISTICS: 'cuisine_characteristics.pickle'
SAFE_REQUEST_INTERVAL: [1, 4]