PREPSTEPS = [
    "finely minced",
    "coarsely minced",
    "minced",
    "finely ground",
    "coarsely ground",
    "ground",
    "seeded",
    "thinly sliced",
    "sliced",
    "finely chopped",
    "coarsely chopped",
    "chopped",
    "cubed",
    "freshly cracked",
    "diced",
    "beaten",
    "whipped",
    "very finely shredded",
    "finely shredded",
    "shredded",
    "packed",
    "divided",
    "drained",
    "crushed",
    "cooked",
    "rinsed",
    "grated",
    "peeled",
    "pitted",
    "softened",
    "casings removed",
    "cut into 2 inch pieces",
    "husked",
    "juiced",
    "cut into wedges",
    "crumbled",
    "trimmed and cut into 3/4-inch pieces",
    "cut in half lengthwise",
    "cut in quaters lengthwise",
    "cut in half",
    "cut in quarters"
]
