PREPSTEPS = [
    "minced",
    "finely minced",
    "ground",
    "finely ground",
    "seeded",
    "sliced",
    "thinly sliced",
    "chopped",
    "finely chopped",
    "cubed",
    "diced",
    "very finely shredded",
    "finely shredded",
    "shredded",
    "packed",
    "divided",
    "drained",
    "crushed",
    "cooked",
    "rinsed",
    "grated"
]
