
# List of tools obtained from: https://github.com/rromo12/EECS-337-Recipe-Transformer-Team-9
# That repo is MIT licensed. Here is the corresponding license text:
#
#     The MIT License (MIT)
#     
#     Copyright (c) 2016 milara
#     
#     Permission is hereby granted, free of charge, to any person obtaining a copy
#     of this software and associated documentation files (the "Software"), to deal
#     in the Software without restriction, including without limitation the rights
#     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#     copies of the Software, and to permit persons to whom the Software is
#     furnished to do so, subject to the following conditions:
#     
#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.
#     
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.
#
# Some modifications were made by Mike D'Arcy
#
COOKING_TOOLS = [
"absinthe spoon",
"adjustable V-rack",
"aluminium foil",
"aluminum foil",
"aluminum stock pan",
"anodized aluminum nonstick pan",
"apple corer",
"apple cutter",
"auto reignition",
"bachelor griller",
"bags",
"baking cups",
"baking dish",
"baking pan",
"baking sheet",
"baking sheets",
"baking stone",
"bamboo stove",
"barbecue",
"barbecue grill",
"bar spoon",
"basket rack",
"baster",
"beanpot",
"bedrock mortar",
"beehive oven",
"berry spoon",
"big green egg",
"biscuit cutter",
"biscuit press",
"blender",
"blow torch",
"board",
"boil over preventer",
"bottle opener",
"bottle scraper",
"bowl",
"braiser pan",
"brasero",
"brazier pot",
"bread knife",
"bread machine",
"bread pan",
"broiler pan",
"browning tray",
"brush",
"burjiko",
"burner",
"butane torch",
"butcher block",
"butcher paper",
"butter churn",
"butter curler",
"caddy spoon",
"cake and pie server",
"cake pan",
"can",
"candy thermometer",
"can opener",
"carbon steel pan",
"casserole",
"casserole pan",
"cassole",
"cast iron dutch oven",
"cast iron skillet",
"chakla",
"chambers stove",
"cheesecloth",
"cheese knife",
"cheesemelter",
"cheese scoop",
"cheese slicer",
"cherry pitter",
"chestnut pan",
"chinoise",
"chip pan",
"chocolatera",
"chopper",
"chorkor oven",
"churchkey",
"clean-burning stove",
"clome oven",
"cloth",
"cocktail stick",
"coffee filter",
"coffeemaker",
"coffee percolator",
"colander",
"comal (cookware)",
"combi steamer",
"communal oven",
"community Cooker",
"convection microwave",
"convection oven",
"cooker",
"cookie cutter",
"cookie press",
"cookie sheet",
"cooking pot",
"cooking sheet",
"cook stove",
"cooling racks",
"copper hand hammered brazing pot",
"copper sauce pan",
"corkscrew",
"corn roaster",
"corn zipper",
"crab cracker",
"crepe maker",
"crepe pan",
"cube tray",
"cuisinart",
"cupcake liners",
"cutting board",
"decorating pen",
"deep fryer",
"diffuser",
"dish",
"double boiler",
"doufeu",
"dough blender",
"dough scraper",
"dutch oven",
"earth oven",
"ecoZoom",
"egg beater",
"eggbeater",
"egg piercer",
"egg poacher",
"egg separator",
"egg slicer",
"egg timer",
"egg topper",
"electric cooker",
"electric kettle",
"electric stove",
"electric water boiler",
"embossing mat",
"energy regulator",
"field kitchen",
"fillet knife",
"fire pot",
"fish scalar",
"flat iron grill pan",
"flat rack",
"flattop grill",
"flesh-hook",
"floor sifter",
"flour sifter",
"foil",
"fondue pot",
"food mill",
"food processor",
"food steamer",
"fork",
"foukou",
"freezer tray",
"frosting spatula",
"fruit muddler",
"frying pan",
"frying skillet",
"fry pan",
"fufu Machine",
"funnel",
"garlic press",
"gas stove",
"glass baking pan",
"gloves",
"grapefruit knife",
"grate and slice set",
"grater",
"gratine pan",
"gravy strainer",
"greaseproof paper",
"griddle",
"grill pan",
"grinder",
"halogen oven",
"hand held electric mixer",
"haybox",
"herb chopper",
"hibachi",
"hoang Cam stove",
"hobo stove",
"horno",
"hot Box (appliance)",
"hot plate",
"hullster",
"induction cooking",
"juicer",
"juicer press",
"kamado",
"karahi",
"kettle",
"kitchener range",
"kitchen knife",
"kitchen oven",
"kitchen stove",
"kitchen utensil",
"knife",
"krampouz",
"kujiejun",
"kyoto box",
"ladle",
"lame",
"lemon reamer",
"lemon squeezer",
"lid",
"lifter",
"lighter",
"loaf pan",
"lobster pick",
"lo trau",
"mandoline",
"masonry oven",
"mated colander pot",
"measuring cup",
"measuring cups",
"measuring jug",
"measuring spoon",
"meat grinder",
"meatloaf pan",
"meat tenderizer",
"meat thermometer",
"melon baller",
"mess kit",
"mezzaluna",
"microplane",
"microwave",
"microwave oven",
"milk watcher",
"mincer",
"mister",
"mixing bowl",
"mortar",
"mortar and pestle",
"mouli grater",
"muffin papers",
"multi-fuel stove",
"mushroom cloth",
"nomiku",
"nonadjustable V-rack",
"nonstick skillet",
"nutcracker",
"nutmeg grater",
"omelette pan",
"oven",
"oven bag",
"oven glove",
"oXO (brand)",
"p-38 can opener",
"paella pan",
"palayok",
"pan",
"paper warp",
"parchment paper",
"parchment roll",
"pasta spoon",
"pastry bag",
"pastry blender",
"pastry brush",
"pastry wheel",
"peeler",
"peel (tool)",
"pepper grinder",
"pepper mill",
"pestle",
"pie bird",
"pie pan",
"pizza cutter",
"pizza wheel",
"plastic bag",
"plastic wrap",
"plate",
"popcorn maker",
"potato masher",
"potato ricer",
"pot boiler",
"pot holder",
"pothook",
"poultry shears",
"pourer",
"press",
"pressure cooker",
"primus stove",
"probe",
"pudding basin",
"pudding cloth",
"pyrex baking dish",
"rack",
"Ramekin",
"red Cross stove",
"reflector oven",
"remoska",
"rice cooker",
"rice polisher",
"ricer",
"rice spoon",
"roasting jack",
"roasting pan",
"roasting pan with high cover",
"roasting rack",
"rocket mass heater",
"rocket stove",
"roller docker",
"rolling pin",
"rondeau",
"round cake pan",
"russian oven",
"sabbath mode",
"salad spoon",
"salamander broiler",
"salt and pepper shakers",
"salt shaker",
"samovar",
"sandwich toaster",
"saran (plastic)",
"saucepan",
"saucier",
"saute pan",
"saute spoon",
"sauteuse pan",
"scale",
"scales",
"scissors",
"scoop",
"scotch hands",
"scraper",
"scraper (kitchen)",
"seal",
"self-cleaning oven",
"serve ladle",
"serving spoon",
"serving tongs",
"shaker",
"shear",
"shellfish scraper",
"shichirin",
"shield",
"sieve",
"sigri (stove)",
"silpat",
"skewer",
"skillet",
"skimmer",
"slicer",
"slotted spoon",
"slow cooker",
"smoother",
"snips",
"solar cooker",
"soup ladle",
"soy milk maker",
"spatula",
"spider",
"spill stopper",
"splatter screen",
"spoon",
"springform pan",
"spurtle",
"Stainless steel pan",
"Stir-fry pan",
"stockpot",
"stopper",
"stove",
"strainer",
"stripper",
"sugar nips",
"sugar spoon",
"sugar thermometer",
"sugar tong",
"sujeo",
"susceptor",
"tablespoon",
"tabun oven",
"tajine",
"tamis",
"tandoor",
"tangia",
"tava",
"tea ball",
"tea infuser",
"tea stove",
"teflon coated frying pan",
"thermal immersion circulator",
"thermometer",
"timbale",
"timer",
"tin foil",
"tin opener",
"toaster",
"toaster oven",
"tomato knife",
"tommy cooker",
"tongs",
"trivection oven",
"trivet",
"trojan Room coffee pot",
"trussing needle",
"turkey fryer",
"two burner griddle pan",
"utensil",
"vacuum fryer",
"vegetable peeler",
"vertical rack",
"waffle iron",
"wax paper",
"wet grinder",
"wheel",
"whisk",
"wok",
"wonder pot",
"wood-burning stove",
"wooden spoon",
"wood-fired oven",
"wrangler",
"yogurt maker",
"zester",
]
